// user
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_USER = 'USER_USER'
export const USER_USERS = 'USER_USERS'
// sort
export const SORT_CREATEDSORT = 'SORT_CREATEDSORT'
export const SORT_SORT = 'SORT_SORT'
export const SORT_SORTS = 'SORT_SORTS'
// topic
export const TOPIC_CREATEDTOPIC = 'TOPIC_CREATEDTOPIC'
export const TOPIC_TOPIC = 'TOPIC_TOPIC'
export const TOPIC_TOPICS = 'TOPIC_TOPICS'
// comment
export const COMMENT_CREATEDCOMMENT = 'COMMENT_CREATEDCOMMENT'
export const COMMENT_COMMENT = 'COMMENT_COMMENT'
export const COMMENT_COMMENTS = 'COMMENT_COMMENTS'