// user
export const USER_SIGNUP = 'USER_SIGNUP'
export const USER_SIGNIN = 'USER_SIGNIN'
export const USER_USER = 'USER_USER'
export const USER_USERS = 'USER_USERS'
// node
export const NODE_CREATEDNODE = 'NODE_CREATEDNODE'
export const NODE_NODE = 'NODE_NODE'
export const NODE_NODES = 'NODE_NODES'
// topic
export const TOPIC_CREATEDTOPIC = 'TOPIC_CREATEDTOPIC'
export const TOPIC_TOPIC = 'TOPIC_TOPIC'
export const TOPIC_TOPICS = 'TOPIC_TOPICS'
// comment
export const COMMENT_CREATEDCOMMENT = 'COMMENT_CREATEDCOMMENT'
export const COMMENT_COMMENT = 'COMMENT_COMMENT'
export const COMMENT_COMMENTS = 'COMMENT_COMMENTS'